name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # каждые 10 минут

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping site
        run: curl -s https://obi-vatan.onrender.com/api/orders > /dev/null
